spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver # 서비스 이름
            client-id: NEkVRBvo7Qw88CHlGq3Z # 서비스에서 발급 받은 ID
            client-secret: Hrfz9lKig0 # 서비스에서 발급 받은 PW
            redirect-uri: http://localhost:8080/login/oauth2/code/naver # 서비스에 등록한 로그인 성공 URI
            authorization-grant-type: authorization_code # 총 4가지 인증 방식 중 코드 방식 선택
            scope:  # 리소스 서버에서 가져올 데이터 범위
              - name,email

#          google:
#            client-name:
#            client-id:
#            client-secret:
#            redirect-uri:
#            authorization-grant-type: authorization_code
#            scope:
#              -

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize # 인증 서버 로그인 URI
            token-uri: https://nid.naver.com/oauth2.0/token # 인증 서버 토큰 URI
            user-info-uri: https://openapi.naver.com/v1/nid/me # 인증 서버 사용자 정보 URI
            user-name-attribute: response # 응답 데이터 변수

#          google:
#            authorization-uri:
#            token-uri:
#            user-info-uri:
#            user-name-attribute: